proyectocoder/Appfinal/urls.py
from django.urls import path

from Appfinal import views


app_name='Appfinal'
urlpatterns = [
    path('', views.index, name='Index'),
    path('Peliculas/', views.Movies, name='Peliculas'),
    path('Sucursales/', views.Sucursal, name='Sucursales'),
    path('Contactos/', views.Contacto, name='Contactos'),
    path('PeliculasFormulario/', views.PeliculasForm, name='PeliculasFormulario'),
    path('SucursalesFormulario/', views.SucursalesForm, name='SucursalesFormulario'),
    path('ContactosFormulario/', views.ContactosForm, name='ContactosFormulario'),
    path('Search/', views.Search, name='Search'),



]

proyectocoder/proyectocoder/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('Appfinal/', include('Appfinal.urls')),
]

proyectocoder/Appfinal/models.py
from django.db import models

# Create your models here.


class Peliculas(models.Model):
    titulo = models.CharField(max_length=40)
    duracion = models.IntegerField()
    emision = models.DateField()

class Sucursales(models.Model):
    ciudad = models.CharField(max_length=40)
    calle = models.CharField(max_length=40)
    altura = models.IntegerField()

class Contactos(models.Model):
    social = models.CharField(max_length=40)
    Telefono = models.IntegerField()
    

proyectocoder/Appfinal/forms.py
import datetime
from django import forms
from django.forms import ModelForm
#from Appfinal.models import *


class PeliculasFormulario(forms.Form):

    titulo = forms.CharField(max_length=40)
    duracion = forms.IntegerField()
    emision = forms.DateField(widget=forms.TextInput(attrs={'placeholder': 'yyyy-mm-dd'}))

class SucursalesFormulario(forms.Form):

    ciudad = forms.CharField(max_length=40)
    calle = forms.CharField(max_length=40)
    altura = forms.IntegerField()

class ContactosFormulario(forms.Form):
    social = forms.CharField(max_length=40)
    Telefono = forms.IntegerField()
    

proyectocoder/Appfinal/views.py
from urllib import request
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render
from django.template import loader
from Appfinal.models import Peliculas, Sucursales, Contactos
from Appfinal.forms import *
import datetime

def index(request):
    return render(request, "Appfinal/index.html")

def Movies(request):
    Movies = Peliculas.objects.all()

    context_dict = {
        'Movie': Movies
    }

    return render(
        request=request,
        context=context_dict,
        template_name="Appfinal/Peliculas.html"
    )

def PeliculasForm(request):
    if request.method == 'POST':
        peliculas = PeliculasFormulario(request.POST)
        print(peliculas)

        if peliculas.is_valid:
            info = peliculas.cleaned_data
            movie = Peliculas (titulo = info['titulo'], 
            duracion = info['duracion'],
            emision = info['emision'])

            movie.save()
            Movies = Peliculas.objects.all()
            context_dict = {'Movie': Movies}
    
            return render(
             request=request,
             context=context_dict,
             template_name="Appfinal/Peliculas.html")
    else:
        peliculas = PeliculasFormulario()
    return render(request, "Appfinal/PeliculasFormulario.html", {"peliculas":peliculas})


def Sucursal(request):
    Sucursal = Sucursales.objects.all()

    context_dict = {
        'Places': Sucursal
    }

    return render(
        request=request,
        context=context_dict,
        template_name="Appfinal/Sucursales.html"
    )

def SucursalesForm(request):
    if request.method == 'POST':
        sucursales= SucursalesFormulario(request.POST)
        print(sucursales)

        if sucursales.is_valid:
            info = sucursales.cleaned_data
            place = Sucursales (ciudad = info['ciudad'], 
            calle = info['calle'],
            altura = info['altura'])

            place.save()
            Sucursal = Sucursales.objects.all()
            context_dict = {'Places': Sucursal}

            return render(
             request=request,
             context=context_dict,
             template_name="Appfinal/Sucursales.html")
    else:
        sucursales = SucursalesFormulario()
    return render(request, "Appfinal/SucursalesFormulario.html", {"sucursales":sucursales})

def Contacto(request):
    Contacto = Contactos.objects.all()

    context_dict = {
        'social': Contacto
    }

    return render(
        request=request,
        context=context_dict,
        template_name="Appfinal/Contactos.html"
    )

def ContactosForm(request):
    if request.method == 'POST':
       contactos= ContactosFormulario(request.POST)
       print(contactos)

       if contactos.is_valid:
            info = contactos.cleaned_data
            Redes = Contactos (social = info['social'], 
            Telefono = info['Telefono'])

            Redes.save()
            Contacto = Contactos.objects.all()
            context_dict = {'social': Contacto}

            return render(
                request=request,
                context=context_dict,
                template_name="Appfinal/Contactos.html")
    else:
        contactos = ContactosFormulario()
    return render(request, "Appfinal/ContactosFormulario.html", {"contactos":contactos})


def Search(request):
    context_dict = dict()
    if request.GET['titulo_search']:
        search_param = request.GET['titulo_search']
        Movies = Peliculas.objects.filter(titulo__contains=search_param)
        context_dict = {
            'Movie': Movies
        }    

    return render(
        request=request,
        context=context_dict,
        template_name="Appfinal/Peliculas.html",
    )

proyectocoder/Appfinal/templates/Appfinal/Contactos.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Contactanos en:</h2>
<hr></hr>
<ul>
    {% for Contacto in social %}
        <li>
            social: {{Contacto.social}} 
           -- Telefono: {{Contacto.Telefono}}
            
        </li>
    {% endfor %}
</ul>

{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/ContactosFormulario.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Formulario para agregar un Contacto al portal</h2>
<hr></hr>
<body>
    <h1>
        {% if contactos.errors %}
        <p style="color: red;"> Datos erroneos, revisar.</p>
        {% endif %}
    </h1>
<form action="" method="POST">
    {% csrf_token %}

    <table>
        {{ contactos.as_table }}
    </table>

    <input type="submit", value="Enviar">
</form>

</body>
{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/Peliculas.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Cartelera de Peliculas</h2>
<form action="/Appfinal/Search" method="GET">
    <div>
        <input type="text" name="titulo_search" id="titulo" placeholder="BUSQUEDA POR TITULO">
        <input type="submit" value="BUSCAR POR TITULO">
    </div>

</form>

<hr></hr>

{% if Movies %}
    <ul>
        {% for Movies in Movie %}
            <li>
                Pelicula: {{Pelicula.titulo}}
                
            </li>
        {% endfor %}
    </ul>
{% endif %}



<hr></hr>
<ul>
    {% for Movies in Movie %}
        <li>
            Pelicula: {{Movies.titulo}} 
           -- Duracion: {{Movies.duracion}}
           -- Emision: {{Movies.emision}}

            
        </li>
    {% endfor %}
</ul>

{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/PeliculasFormulario.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Formulario para agregar una Pelicula a la cartelera</h2>
<hr></hr>
<body>
    <h1>
        {% if peliculas.errors %}
        <p style="color: red;"> Datos erroneos, revisar.</p>
        {% endif %}
    </h1>
<form action="" method="POST">
    {% csrf_token %}

    <table>
        {{ peliculas.as_table }}
    </table>

    <input type="submit", value="Enviar">
</form>

</body>
{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/Sucursales.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Sucursales en Buenos Aires</h2>
<hr></hr>
<ul>
    {% for Sucursal in Places %}
        <li>
            Ciudad: {{Sucursal.ciudad}} 
           -- Calle: {{Sucursal.calle}}
           -- Altura: {{Sucursal.altura}}
            
        </li>
    {% endfor %}
</ul>

{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/SucursalesFormulario.html
{% extends "Appfinal/index.html" %}
{% load static %}
{% block Appfinal_content %}

<h2>Formulario para agregar una Sucursal al portal</h2>
<hr></hr>
<body>
    <h1>
        {% if sucursales.errors %}
        <p style="color: red;"> Datos erroneos, revisar.</p>
        {% endif %}
    </h1>
<form action="" method="POST">
    {% csrf_token %}

    <table>
        {{ sucursales.as_table }}
    </table>

    <input type="submit", value="Enviar">
</form>

</body>
{% endblock %}

proyectocoder/Appfinal/templates/Appfinal/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{{ settings.app_name }}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Appfinal/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">CINEMA PY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Appfinal:Index' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Appfinal:Peliculas' %}">Peliculas</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Appfinal:Sucursales' %}">Sucursales</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Appfinal:Contactos' %}">Contactos</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block Appfinal_content %}
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://cdn-icons-png.flaticon.com/512/2809/2809591.png" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">CINEMA PY</h1>
                    <p>ELIGE TU PELICULA Y DISFRUTA!</p>
                    <a class="btn btn-primary" href="#!">RESERVA!</a>
                </div>
                
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://i.gifer.com/embedded/download/5sB4.gif" alt="..." /></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">ADMINISTRAR CARTELERA </h2>
                            <p class="card-text">AÑADA UNA PELICULA A LA CARTELERA</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'Appfinal:PeliculasFormulario' %}">AÑADIR</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">ADMINISTRAR SUCURSALES</h2>
                            <p class="card-text">AÑADA UNA SUCURSAL AL PORTAL.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'Appfinal:SucursalesFormulario' %}">AÑADIR</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">ADMINISTRAR CONTACTOS</h2>
                            <p class="card-text">AÑADA CONTACTOS AL PORTAL</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'Appfinal:ContactosFormulario' %}">AÑADIR</a></div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark"> 
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Proyecto Coder 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>